/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Call Details
     * Obtener detalles de una llamada específica
     * @param callId 
     */
    getCallDetailsApiCallsCallIdGet(callId: number, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Get Calls
     * Obtener lista de llamadas recientes
     * @param skip 
     * @param limit 
     */
    getCallsApiCallsGet(skip?: number, limit?: number, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Get Openapi Yaml
     * Descargar OpenAPI en YAML
     */
    getOpenapiYamlApiOpenapiYamlGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Search Calls
     * Buscar llamadas por número de teléfono
     * @param phone 
     */
    searchCallsApiSearchGet(phone: string, extraHttpRequestParams?: any): Observable<any>;

}
