/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Inicio
     * Endpoint para cuando comienza la llamada
     */
    inicioInicioPost(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Recording
     * Endpoint que recibe el callback de la grabación de Twilio. Twilio enviará RecordingUrl y otros metadatos. Aquí simplemente confirmamos la recepción y agradecemos al usuario. En un siguiente paso podríamos descargar la grabación y transcribirla con un servicio ASR externo.
     */
    recordingRecordingPost(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Root
     * 
     */
    rootGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Serve Audio
     * Endpoint para servir archivos de audio
     * @param filename 
     */
    serveAudioAudioFilenameGet(filename: string, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Voice
     * 
     */
    voiceVoicePost(extraHttpRequestParams?: any): Observable<any>;

}
