/**
 * ORISOD Enzyme® Voice Assistant API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CallRequest } from '../model/models';
import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Handle Outgoing Call Get
     * Handle outgoing call webhook (GET) and return TwiML response.
     */
    handleOutgoingCallGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Handle Outgoing Call Post
     * Handle outgoing call webhook (POST) and return TwiML response.
     */
    handleOutgoingCallPost(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Handle Recording Status
     * Handle recording status updates from Twilio.
     */
    handleRecordingStatus(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Health Check
     * Health check endpoint.
     */
    healthCheckGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Make Call
     * Initiate an outbound call to the specified phone number.
     * @param callRequest 
     */
    makeCallMakeCallPost(callRequest: CallRequest, extraHttpRequestParams?: any): Observable<any>;

}
