/**
 * ORISOD Enzyme® Voice Assistant API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Interaction log entry.
 */
export interface InteractionLog { 
    user: string;
    ai: string;
    timestamp: number;
}


